name: Greetings

on:
  workflow_call:

jobs:
  greeting:
    runs-on: ${{ vars.RUNNER }}

    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 **Hello and welcome!**

          Thanks for opening your very first issue! We appreciate your feedback and interest in improving DataKit.

          The maintainers will review your issue shortly. In the meantime, consider joining our [Discord](https://dtkt.dev/join-discord) for discussions or additional support.

          Happy contributing! 🚀

        pr-message: |
          🎉 **Congrats on your first Pull Request!**

          Thanks for contributing to DataKit! We're thrilled to have your input.

          The maintainers will review your PR shortly. In the meantime, ensure you've checked out our [contribution guidelines](CONTRIBUTING.md) and feel free to join our community on [Discord](https://dtkt.dev/join-discord).

          Keep up the great work! ✨
